#!/bin/bash
yellow='\[$(tput setaf 3)\]'
red='\[$(tput setaf 1)\]'
white='\[$(tput setaf 7)\]'
green='\[$(tput setaf 2)\]'
bold='\[$(tput bold)\]'
blue='\[$(tput setaf 4)\]'
purple='\[$(tput setaf 5)\]'
reset='\[$(tput sgr 0)\]'
