#!/bin/bash
function gitbranch {
    branches="$(git branch 2> /dev/null)"
    if [[ $? != 0 ]]; then
        return
    fi
    result=$(echo "$branches" | grep '^* ' | grep -o '[^*][^ ].*')
    echo $result
}

function addpath {
    PATH=$(~/bin/addpath.py $1)
}

function delpath {
    PATH=$(~/bin/delpath.py $1)
}

preexec () { tput sgr0; }
preexec_invoke_exec () {
    [ -n "$COMP_LINE" ] && return  # do nothing if completing
    local this_command=`history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g"`;
    preexec "$this_command"
}
trap 'preexec_invoke_exec' DEBUG
