#!/bin/bash

function resource {
    pushd ~/.shell_setup > /dev/null
    source ~/.shell_setup/bashrc
    popd > /dev/null
}

preexec () { tput sgr0; }
preexec_invoke_exec () {
    [ -n "$COMP_LINE" ] && return  # do nothing if completing
    local this_command=`history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g"`;
    preexec "$this_command"
}
trap 'preexec_invoke_exec' DEBUG
