#!/bin/bash
function gitbranch {
    branches="$(git branch 2> /dev/null)"
    if [[ $? != 0 ]]; then
        return
    fi
    result=$(echo "$branches" | grep '^* ' | grep -o '[^*][^ ].*')
    echo $result
}

function insertpath {
    PATH=$(~/.shell_setup/bin/addpath.py --path $1 --at $2)
}

function addpaths {
    PATH=$(~/.shell_setup/bin/addpath.py --pathfile $1)
}

function addpath {
    PATH=$(~/.shell_setup/bin/addpath.py --path $1 --at 0)
}

function delpath {
    PATH=$(~/.shell_setup/bin/delpath.py $1)
}

function mysource {
    source ~/.shell_setup/$1
}

function resource {
    pushd ~/.shell_setup > /dev/null
    source ~/.shell_setup/bashrc
    popd > /dev/null
}

preexec () { tput sgr0; }
preexec_invoke_exec () {
    [ -n "$COMP_LINE" ] && return  # do nothing if completing
    local this_command=`history 1 | sed -e "s/^[ ]*[0-9]*[ ]*//g"`;
    preexec "$this_command"
}
trap 'preexec_invoke_exec' DEBUG
