#!/bin/bash
red='\[$(tput setaf 1)\]'
white='\[$(tput setaf 7)\]'
green='\[$(tput setaf 2)\]'
bold='\[$(tput bold)\]'
blue='\[$(tput setaf 4)\]'
PS1="$red\u$white@$green\h$white [] $blue\w $white\$ "
